FIX `num_points` parameter deprecation in `imagepolygon()`
laminas/laminas-barcode pull request #24
Opened 2024-05-10 14:35 UTC by ls-youssef-jlidat

|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | yes
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description

The parameter `num_points` has been deprecated in PHP 8.1
https://www.php.net/manual/en/function.imagepolygon.php

2024-05-16 13:16 UTC, froschdesign requested changes

2024-05-16 13:16 UTC, froschdesign commented on src/Renderer/Image.php
> +            }
This part is not necessary as PHP version 8.1 is the minimum for this package:

https://github.com/laminas/laminas-barcode/blob/e8e85eb77c0b9768846e7e97a285485790e4f942/composer.json#L27-L28

2024-05-16 14:50 UTC, ls-youssef-jlidat commented on src/Renderer/Image.php
> +            }
Good point! I removed the version check and the usage of `$numPoints` (It's assumed to be `count($points)/2`)

2024-06-13 18:29 UTC, ls-youssef-jlidat commented
Hey @froschdesign, Is there any chance we could get this one merged soon? It'll really help us move forward with our PHP 8.3 upgrade. Thanks a bunch!

2024-06-13 20:26 UTC, gsteel approved these changes
Thanks @ls-youssef-jlidat

2024-06-13 20:29 UTC, merged