Move classes from Object namespace to Barcode namespace
laminas/laminas-barcode pull request #4
Opened 2020-02-22 13:21 UTC by simivar

|    Q          |   A
|-------------- | ------
| Documentation | yes
| Bugfix        | yes
| BC Break      | no
| New Feature   | no
| RFC           | yes
| QA            | no

### Description
Looking at #1 I decided to try and move all the classes from `Laminas\Barcode\Object` namespace to `Laminas\Barcode\Barcode` namespace. I had some problems with it as there are several classes that are children of another class. In order to not break the chain of inheritance that's currently in the repository I introduced `ObjectInheritanceTest`. 

The thing I am not sure about is is whether I should move tests to test `Barcode` classes instead of `Object` ones?

2020-02-25 09:25 UTC, froschdesign commented
@simivar 
Can you check also the first code example in the "Barcode Objects" section:

> ```php
> use Laminas\Barcode\Object;
> 
> $options = ['text' => 'ZEND-FRAMEWORK', 'barHeight' => 40];
> 
> // Case 1: constructor
> $barcode = new Object\Code39($options);
> 
> // Case 2: setOptions()
> $barcode = new Object\Code39();
> $barcode->setOptions($options);
> 
> // Case 3: individual setters
> $barcode = new Object\Code39();
> $barcode->setText('ZEND-FRAMEWORK')
 >   ->setBarHeight(40);
> ```

https://github.com/laminas/laminas-barcode/blob/master/docs/book/objects.md#different-ways-to-parameterize-a-barcode-object

(I will do the renaming of the page and the setup of the forwarding later.)

2020-02-25 10:22 UTC, simivar commented
@froschdesign Done.

2020-02-25 11:08 UTC, froschdesign commented
@simivar 
> …merging this should not result in BC Break as old classes are still there just with @deprecated annotation.

You are right! 👍

2020-02-26 21:04 UTC, froschdesign commented
@simivar 
> The thing I am not sure about is is whether I should move tests to test `Barcode` classes instead of `Object` ones?

At some point the classes must be moved, so the question is: if not now, then when?

2020-02-27 20:49 UTC, weierophinney requested changes
First off, thanks for taking the initiative on this! I really appreciate the work you've put into it!

However, I think it needs some changes in order to (a) fulfill existing inheritance, and (b) create a new inheritance hierarchy.

This is what I propose, and why:

- `Laminas\Barcode\Barcode\BarcodeInterface` should *extend* `Laminas\Barcode\Object\ObjectInterface`, defining all of the same methods. This allows the _new implementations_ to implement both interfaces, allowing them to fulfill both typehints.

- `Laminas\Barcode\Object\AbstractObject` should remain abstract and implement `Laminas\Barcode\Object\ObjectInterface`, but be empty.

- `Laminas\Barcode\Barcode\AbstractBarcode` should extend `Laminas\Barcode\Object\AbstractObject`, implement `Laminas\Barcode\Barcode\BarcodeInterface`, and have the full body of the code currently in `AbstractObject`. This allows all extensions of it to implement each of `ObjectInterface` and `BarcodeInterface`, as well as fulfill both the `AbstractObject` and `AbstractBarcode` types. (I tested this locally, and it worked correctly with regards to inheritance and typehinting; I can provide a gist if necessary).

For the next major release, then, all we'd need to do is:

- Remove the `Object` subdirectory
- Remove the extension of `ObjectInterface` in `BarcodeInterface`
- Remove the extension of `AbstractObject` in `AbstractBarcode`

Does that all make sense?

I've also provided a few other notes below.

Again, thanks!

2020-02-27 20:49 UTC, weierophinney commented on src/Barcode.php
>      public static function getObjectPluginManager()
We should add a `getBarcodePluginManager()` to this class as well, and have this particular method proxy to that one; otherwise users may get confused at the "Object" notation.

2020-02-27 20:49 UTC, weierophinney commented on src/Barcode.php
>      protected static $objectPlugins;
I'd rename this to `$barcodePlugins`. We tend to consider the `protected` API as non-public, making this okay to change. When you do, make sure you update any code referencing the property, both here and in the tests.

2020-02-28 17:27 UTC, simivar commented
@weierophinney I don't know if I understood you correctly but... if we move all the code from `AbstractObject` to `AbstractBarcode` and have `AbstractBarcode extends AbstractObject` wouldn't that be a BC break? If someone has class that *extends* `AbstractObject` it would stop working as all the code would be gone.

2020-02-28 19:26 UTC, froschdesign commented
@weierophinney 
> * `Laminas\Barcode\Object\AbstractObject` should remain abstract and implement `Laminas\Barcode\Object\ObjectInterface`, but be empty.
> * `Laminas\Barcode\Barcode\AbstractBarcode` should extend `Laminas\Barcode\Object\AbstractObject`…

If `AbstractObject` is empty then it must extend `AbstractBarcode`, right?

> I can provide a gist if necessary

That would be help here.
 
/cc @simivar

2020-03-02 15:14 UTC, weierophinney commented
@simivar — Right - I got this a little backwards. Do what @froschdesign suggests: have `AbstractObject` extend `AbstractBarcode`, and not vice versa, as that gives us the inheritance we need to ensure BC. (But still move the implementation into `AbstractBarcode`.)

2020-03-04 16:18 UTC, simivar commented
Done.

/cc @weierophinney @froschdesign

2020-03-04 21:50 UTC, froschdesign commented
@simivar 
Thank you for your time and this contribution!

Unfortunately not everything fits yet.

The goal of this pull request is a deprecation of the old namespace and classes this means for the next major no rewrite of code is needed. Only some removals.

See: https://github.com/laminas/laminas-barcode/pull/4#pullrequestreview-365941476

> For the next major release, then, all we'd need to do is:
> * Remove the `Object` subdirectory
> * Remove the extension of `ObjectInterface` in `BarcodeInterface`
> * Remove the extension of `AbstractObject` in `AbstractBarcode`

And the remove of `test\Object` subdirectory.

A review will follow shortly. Thanks for your patience!

2021-02-10 21:45 UTC, weierophinney commented
Dropping this from the 2.9.0 release for a variety of reasons, not least of which is the original branch has been deleted, but primarily because [we voted to mark this package security-only](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only). As such, a v3 release is unlikely at this time. We can revisit if/when we decide differently.

2021-02-16 00:27 UTC, closed without merging